### ISSUE TITLE
Explain the Algorithms in English.

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/Algorithms-Explanation#1]
Please write the explanation and steps of the algorithms implemented in other repositories of this organization and follow the template given in the README.md file. 

NOTE : For each algorithm create a ```.md``` file and send a Pull Request.

**Comment by shubhammatta** [comment]
@AnupKumarPanwar 
Is this issue taken? 
I can work on this if you need an extra set of hands.. :+1:

**Comment by varunu28** [comment]
@AnupKumarPanwar  @dynamitechetan 
Can we use [Linear Search](https://github.com/TheAlgorithms/Algorithms-Explainations/blob/master/Search%20Algorithms/Linear%20Search.md) as a model for future additions so that there is a common framework to follow

**Comment by vvyomjjain** [comment]
#16

**Comment by vvyomjjain** [comment]
#16 Just added heap sort markdown and its implementation in cpp, java and python.

**Comment by Jonathan-Montanez** [comment]
I would like to contribute to this. I will add the explanation for Bellman Ford in Python.
