### ISSUE TITLE
Floyd Cycle Detection Algorithm Explanation

### ISSUE THREAD

**Issue by Swastyy** [TheAlgorithms/Algorithms-Explanation#116]
Can I write a code explanation in en/search/ to detect a duplicate number in an array using Floyd Algorithm?

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository in that language.
* Follow the steps mentioned at the [`README.md`](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/README.md).
* Ensure that you include YouTube, Wikipedia, or any other links for algorithm explanation.

I'll look forward to reviewing your PR as soon as I can. Thank you. 🙂

**Comment by Swastyy** [comment]
No don't close it.

**Comment by TheShubham-K** [comment]
is there any update for me @Panquesito7 ?

**Comment by Panquesito7** [comment]
> is there any update for me @Panquesito7 ?

Ahh, sorry 😅 this is the PR, already made by @Swastyy #122.
