### ISSUE TITLE
🐛 Code implementation error 🐛 🐛 

### ISSUE THREAD

**Issue by nivedha02** [TheAlgorithms/Algorithms-Explanation#129]
I tired to view the codes in python ,but it throws an error. 
https://github.com/TheAlgorithms/Python/blob/master/computer_vision/harriscorner.py

**Comment by Panquesito7** [comment]
Please report this issue in the [**Python**](https://github.com/TheAlgorithms/Python) repository. This repository is for explanations of many algorithms. Thank you. 🙂
