### ISSUE TITLE
[OTHER] As mention in the issue #154 there are some links broken not only java once

### ISSUE THREAD

**Issue by AnujSsStw** [TheAlgorithms/Algorithms-Explanation#161]
### What would you like to share?

So I would like to know this 
- is these link generated - by a set of code or do you just type it out
  - if yes can you guys share
  - if not is it not going to be a TDS job to keep fixing this type of thing and keep implementing new links for that part like there is the same problem with the 
![Screenshot (137)](https://user-images.githubusercontent.com/92370865/162044076-ee55995b-16fc-470b-bdce-3e11c229a31d.png)
![Screenshot (138)](https://user-images.githubusercontent.com/92370865/162044081-b7167037-209b-4b5b-86a8-b6547ed25341.png)
c++ link too.

### Would you like to work on this issue?

- [ ] Yes, I want to work on this issue!

**Comment by Panquesito7** [comment]
The link isn't generated; it is copied from its respective repository, such as Java, C++, Python, etc..
