### ISSUE TITLE
[FEATURE] Add a PR template

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Algorithms-Explanation#165]
### Detailed description

Adding a pull request template will make the work for maintainers much easier.

### Context

This would make the review process easier, plus, letting the maintainers/reviewers know what the PR is about, useful information, and more.

### Additional information

If you wanna work on this, feel free to raise a PR. Contributions are always welcome!

**Comment by MukundLadani** [comment]
I want to contribute to this issue. Assign it to me.

**Comment by MukundLadani** [comment]
I have made the required changes please accept my PR with the label "HACKTOBERFEST ACCEPTED" and let me know if there are any further changes.
