### ISSUE TITLE
Add magic square concept in basic maths

### ISSUE THREAD

**Issue by navdiya-nikunj** [TheAlgorithms/Algorithms-Explanation#167]
### What would you like to share?

# magic square in odd order concept

it is a famous square in maths 

i will explain everything about it in basic maths folder..
please assign it to me...

### Would you like to work on this issue?

- [X] Yes, I want to work on this issue!

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository in that language.
* Follow the steps mentioned at the [`README.md`](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/README.md).
* Ensure that you include YouTube, Wikipedia, or any other links for algorithm explanation.

I'll look forward to reviewing your PR as soon as I can. Thank you. 🙂

**Comment by navdiya-nikunj** [comment]
Okay thank you

**Comment by navdiya-nikunj** [comment]
@Panquesito7 i have completed my pr check it out
