### ISSUE TITLE
[FEATURE] Add Kadane's Algorithm 

### ISSUE THREAD

**Issue by shrutikahilale** [TheAlgorithms/Algorithms-Explanation#183]
### Detailed description

Kadane's Algorithm is one of the most useful and powerful dynamic programming algorithm.
Time complexity: O(n)
Space complexity: O(1)

### Context

DSA questions like **Maximum Subarray Sum** requires dynamic programming algorithms to solve them efficiently. In an array, subarrays are the contiguous part inside another array which only contains contiguous elements.

- Maximum Subarray Sum problem states that: Given an array of integers, the task is to find the maximum subarray sum possible of all the non-empty subarrays (meaning the subarray must contain at least one element).

- So, Kadane’s Algorithm is an iterative dynamic programming algorithm. The simple idea is it calculates the maximum subarray sum ending at a particular position by using the maximum subarray ending sum at the previous position.

**Comment by Jiganesh** [comment]
Hello @shrutikahilale I have created a pull request regarding this enhancement. Can you check the [pull request](https://github.com/TheAlgorithms/Algorithms-Explanation/pull/181)

**Comment by shrutikahilale** [comment]
> Hello @shrutikahilale I have created a pull request regarding this enhancement. Can you check the [pull request](https://github.com/TheAlgorithms/Algorithms-Explanation/pull/181)

Amazing work 🚀!!
