### ISSUE TITLE
[OTHER] Link implementations to website

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Algorithms-Explanation#190]
### What would you like to share?

Instead of specifying the implementations in other languages and its link to them, we should probably add an implementation link using [The Algorithms' website](https://the-algorithms.com) (if the algorithm's even available). This way, it will show all implementations with links to them without having to write them down manually.

What do you think about this? Thanks. 🙂

### Would you like to work on this issue?

- [X] Yes, I want to work on this issue!

**Comment by appgurueu** [comment]
Good idea.
