### ISSUE TITLE
Heap sort

### ISSUE THREAD

**Issue by asbaravkar** [TheAlgorithms/Algorithms-Explanation#55]
Need to write more regarding complexities for Build Heap and Heapify.
* Build Heap takes O(n) complexity and not O(n*logn)
* Heapify takes O(logn)

**Comment by AnupKumarPanwar** [comment]
Do you want to work on it?

**Comment by asbaravkar** [comment]
Ya sure !

**Comment by JRaiden16** [comment]
Is this solved?

**Comment by asbaravkar** [comment]
YES
