### ISSUE TITLE
Tree Algorithms

### ISSUE THREAD

**Issue by ridhishjain** [TheAlgorithms/Algorithms-Explanation#58]
## Aim

To create a directory in data structures for trees and adding tree-related algorithm explanations there

## It will include

* Binary Tree and BST implementation as ADT
* Height order traversal: Inorder traversal (both recursive and non-recursive)
* Height order traversal: Preorder traversal (both recursive and non-recursive)
* Height order traversal: Postorder traversal (both recursive and non-recursive)
* Level order traversal (both recursive and non-recursive)
* Vertical order traversal (both recursive and non-recursive)

for BST:
* BST searching
* BST addition
* BST deletion

### NOTE
Including above algos if not already implemented or included in other Repos.

**Comment by ridhishjain** [comment]
thoughts @AnupKumarPanwar ?

**Comment by divyansh12323** [comment]
I would like to work together @ridhishjain

**Comment by ridhishjain** [comment]
Sure, we can work together @divyansh12323 
:+1:

**Comment by ExpressHermes** [comment]
@divyansh12323 @ridhishjain are you guys still working on this as I would like to work on this

**Comment by ridhishjain** [comment]
@ExpressHermes you can go on, we were actually waiting for owners to consider this as valid.
I am not sure if it's required

**Comment by JRaiden16** [comment]
I would like to contribute to this too
