### ISSUE TITLE
Better explanation for LCS

### ISSUE THREAD

**Issue by nvmnghia** [TheAlgorithms/Algorithms-Explanation#65]
Hi, I've been always NOT understanding LCS & DP in general. In [the LCS explaination](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/en/Dynamic%20Programming/Longest%20Common%20Subseqence.md), these sentences

> If we throw `A`, our LCS length will be `dp[i - 1][j]` (since we have prefixes `S[1..i - 1]` and `T[1..j]`). If we try to throw `B` character, we will have prefixes `S[1..i]` and `T[1..j - 1]` so the length of LCS will be `dp[i][j - 1]`.

seem to claim that `dp[i][j] = dp[i - 1][j] = dp[i][j - 1]`, which is not the case.

Can we have a better explanation?

**Comment by Rastrian** [comment]
A = prefix S (1th array)
B = prefix T (2th array)

Its just for represent each values, in the same text he also said based on this: As we are looking for the <b>Longest</b> common subsequence, we will pick <b>the maximum value</b> from `dp[i][j - 1]` and `dp[i - 1][j]`.
