### ISSUE TITLE
Recursive version of algorithms

### ISSUE THREAD

**Issue by AdityaPrakash-26** [TheAlgorithms/Algorithms-Explanation#97]
Hello!

I would like to implement sorting/searching algorithms recursively. While they don't necessarily have an advantage over iterative versions, they can be useful to check one's understanding of the algorithm and recursion.

If this sounds good, I request to be assigned to this issue :-)

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Follow the steps mentioned at the [`README.md`](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/README.md).
* Ensure that you include YouTube, Wikipedia, or any other links for algorithm explanation.

I'll look forward to reviewing your PR as soon as I can. Thank you. 🙂

**Comment by AdityaPrakash-26** [comment]
Thanks, @Panquesito7!

I will start working on this ASAP. Quick question though, you asked me to ensure that:
- The algorithm isn't a duplicate in this repository.

Just to clarify, I can implement `Recursive Bubble Sort` even though the repo has the iterative version of `Bubble Sort`, right?

**Comment by Panquesito7** [comment]
Sure, you can implement that. They are different versions, so everything should be alright. Thanks. 😄
